### PR TITLE
Support SNICallback to allow for dynamic certificate generation

### PR DESCRIPTION
**Pull request by wwerner**
This PR enables using `tls.createServer({SNICallback})`[^1].
In combination with node-forge[^2], this can be used to dynamically generate TLS certificates for upstream hosts signed by a given CA.
Given you control the CA and trust it in your clients, you can have proper SSL verification without sacrificing the possibility to intercept traffic.

To give it a spin, see https://github.com/gr3p1p3/transparent-proxy/pull/26/files#diff-d7a6894773e00d0ed0d867870b34d66a0b434d37ba1117fa6f8ca9f2abe86255R15

[^1]: https://nodejs.org/api/tls.html#tlscreateserveroptions-secureconnectionlistener
[^2]: https://github.com/digitalbazaar/forge

### CODE REVIEW

**Comment by wwerner** [comment]
@gr3p1p3, what's your take on this? Interested in the feature?

**Comment by gr3p1p3** [comment]
I tried a "npm test" on this branch after installing node-forge locally and it didn't  work! I will try this again in the next days.

I need to go deeper on this feature to understand better.

**Comment by wwerner** [comment]
Interesting. `node-forge` is only a devDependency and used in `examples/sniCallback.js`.  It shouldn't be required to run the tests.

Here's what works for me, starting from a clean slate:
```sh
git clone git@github.com:wwerner/transparent-proxy.git
cd transparent-proxy
git co feat/support-sni
npm install # installs dependencies and runs tests successfully

cd examples
node sniCallback.js # starts the proxy w/ dynamic certificate generation
```
In a second shell, run `curl -vvk --proxy localhost:8080 https://httpbin.org/anything`.

You'll see information about the certificate. It is a certificate for httpbin, but issued and signed by Transparent Proxy.
If you trust the CA certificate that was generated (`examples/ca.cert`) on your local machine, you can remove the `-k` switch from curl; the connection can be properly verified then.

This allows you - given a shared private CA - to generate trusted certs for unknown upstream hosts.

`curl` output:
```
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=httpbin.org
*  start date: Mar  2 16:45:36 2023 GMT
*  expire date: Mar  2 16:45:36 2024 GMT
*  issuer: O=transparent-proxy; CN=Transparent Proxy CA
```

**Comment by gr3p1p3** [comment]
Nice, can you use ' instead " for strings? It would be really appreciated.

What if we wrap directly all possible options for https://nodejs.org/api/tls.html#tlscreateserveroptions-secureconnectionlistener 

Instead giving only SNICallback?

**Comment by gr3p1p3** [comment]
I have a problem with my local version of curl while executing `npm test`.
The curl v7.83 doesn't have the right output

```bash
Proxy replied 200 to CONNECT request
* CONNECT phase completed
* schannel: disabled automatic use of client certificate
* ALPN: offers http/1.1
* ALPN: server did not agree on a protocol. Uses default.
> GET / HTTP/1.1
> Host: ifconfig.co
> User-Agent: curl/7.83.1
> Accept: */*
``` 
with curl v7.64 works flawless.

**Pull request merged**
